version: '3.8'

services:
  api-gateway:
    build: api-gateway1
    ports:
      - "8080:8080"
    depends_on:
      - device-ingestion-service

  device-ingestion-service:
    build: ./device-ingestion-service
    depends_on:
      - kafka
      - mysql

  analytics-service:
    build: ./analytics-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mysql
      - rabbitmq
      - python-ml-service

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq

  python-ml-service:
    build: ./python-ml-service
    ports:
      - "5000:5000"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Sharanu@123
      MYSQL_DATABASE: healthcare_db
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
